### ISSUE TITLE
Tests for executable

### ISSUE THREAD

**Issue by JanCBrammer** [IUPAC-InChI/InChI#17]
We collect molfiles that elicit specific behavior (e.g., errors): https://github.com/IUPAC-InChI/InChI_Dev/tree/main/Development/Test_structures/Molfiles

**Comment by giallu** [comment]
Did you already pick a unit testing framework? I am familiar with Catch2 but I guess it's as good as any leading one nowadays. However, I started using that one because of the extremely simple steps I needed to integrate it in the cmake build. If you like, I can provide you with a scaffold to add tests after I finalize the changes for cmake support in #37

**Comment by giallu** [comment]
By the way, the link is 404

**Comment by JanCBrammer** [comment]
> Did you already pick a unit testing framework?

I was considering [pytest](https://docs.pytest.org/en/stable/) (calling InChI via https://docs.python.org/3/library/ctypes.html or https://docs.python.org/3/library/subprocess.html). I'll look into https://github.com/catchorg/Catch2 as well, thanks for the suggestion!

**Comment by JanCBrammer** [comment]
> the link is 404

I should stop referring to https://github.com/IUPAC-InChI/InChI_Dev/, seems pretty volatile.

**Comment by JanCBrammer** [comment]
Closing with 290f5478c0867403dd0d79402892773efee66ce6.

Note that technically, these aren't unit tests. The artifact under test is the InChI executable rather than specific code units. In a sense what's being done here is "black box" testing, expecting the "black box" (i.e., executable) to generate specific results for specific inputs.
