### ISSUE TITLE
Double bond stereo handling regression in version 1.07-beta.3

### ISSUE THREAD

**Issue by IstvanOri** [IUPAC-InChI/InChI#9]
Double bond stereo handling issues discoverd when v1.07-beta.3 was integrated. In Java environment, using the InChI native library via JNI, some double bond stereo related tests failed after upgrading to 1.07-beta3 from 1.06.

Only tested on windows yet, but it seems that not the Java integration is the issue, because can be reproduced (kind of) with the InChI command line tool (exe). Even though the command below runs succsessfully, the result seems incorrect. 

## How to reproduce
Run the following command (tested on windows):
```
inchi-1.exe in.txt /InChI2InChI
```
Where the content of in.txt file is `InChI=1S/C4H8/c1-3-4-2/h3-4H,1-2H3/b4-3+`
## Current behaviour
The result is `InChI=1S/C4H8/c1-3-4-2/h3-4H,1-2H3/b0-0!`, which does not seem valid. 
## Expected behaviour
The result should be the original input.

**Comment by JanCBrammer** [comment]
@IstvanOri, thanks for the report! We'll look into this.

**Comment by djb-rwth** [comment]
I can confirm that the issue with /b-layer has now been fixed and will be added to Beta4 version very soon.

**Comment by djb-rwth** [comment]
Hi Istvan,
`v.1.07-Beta4` has been uploaded, so please check if the issue has been resolved.
Thank you.

**Comment by JanCBrammer** [comment]
@djb-rwth, could you link the closing commit?

**Comment by flange-ipb** [comment]
Closing commit is 4b84561.

The fix is in [INCHI-1-SRC/INCHI_BASE/src/ichiread.c around line 7318](https://github.com/IUPAC-InChI/InChI/commit/4b845611234ceb16c02e69c8cb7ae4e0a25a47f6#diff-b02168c8d87e241808bf63197e533dcfdd4432a0bf772de77ac535c31af2e237L7318).
The regression was introduced [here](https://github.com/IUPAC-InChI/InChI_Dev/commit/4272209c823072502e043efd825fc450ec903cae#diff-b02168c8d87e241808bf63197e533dcfdd4432a0bf772de77ac535c31af2e237R7392) before the 1.07-Beta1 release.

**Comment by IstvanOri** [comment]
Thank you for the fix. I can confirm it works.
It seems (by our automated tests) that in our system the InChI library could be upgraded to 1.07 in its current state.
